services:
    #################
    ### PROVIDERS ###
    #################
    core.provider.mail:
        class: Shop\CoreBundle\Providers\MailProvider
        calls:
            - [setContainer, ["@service_container"]]
    core.provider.mail_contact:
        class: Shop\CoreBundle\Providers\MailContactProvider
        arguments: [%contact_email%, %contact_from%]
        calls:
            - [setMailerProvider, ["@core.provider.mail"]]
    ####################
    ### REPOSITORIES ###
    ####################
    core.repository.category:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Shop\CoreBundle\Entity\Category
    core.repository.product:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Shop\CoreBundle\Entity\Product
    core.repository.page:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Shop\CoreBundle\Entity\Page
    ################
    ### MANAGERS ###
    ################
    core.manager.category:
        class: Shop\CoreBundle\Manager\CategoryManager
        arguments: ['@doctrine.orm.entity_manager', '@core.repository.category']
    core.manager.product:
        class: Shop\CoreBundle\Manager\ProductManager
        arguments: ['@doctrine.orm.entity_manager', '@core.repository.product', '@core.services_file']
    core.manager.page:
        class: Shop\CoreBundle\Manager\PageManager
        arguments: ['@doctrine.orm.entity_manager', '@core.repository.page']
    ################
    ### SERVICES ###
    ################
    core.services_file:
        class: Shop\CoreBundle\Services\FileService
        arguments: ['%image_product_dir%']
